# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_irqConcat_0/design_1_irqConcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_irqConcat_0 || ORIG_REF_NAME==design_1_irqConcat_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_porReset_0/design_1_porReset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_porReset_0 || ORIG_REF_NAME==design_1_porReset_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_psAxiInterconnect_0/design_1_psAxiInterconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_psAxiInterconnect_0 || ORIG_REF_NAME==design_1_psAxiInterconnect_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_psInterruptController_0/design_1_psInterruptController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_psInterruptController_0 || ORIG_REF_NAME==design_1_psInterruptController_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_resetSlice_0/design_1_resetSlice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_resetSlice_0 || ORIG_REF_NAME==design_1_resetSlice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_subprocessorClk_0/design_1_subprocessorClk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_subprocessorClk_0 || ORIG_REF_NAME==design_1_subprocessorClk_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_riscvReset_0/design_1_riscvReset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_riscvReset_0 || ORIG_REF_NAME==design_1_riscvReset_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_riscvBramController_0/design_1_riscvBramController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_riscvBramController_0 || ORIG_REF_NAME==design_1_riscvBramController_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_psBramController_0/design_1_psBramController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_psBramController_0 || ORIG_REF_NAME==design_1_psBramController_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_riscvBram_0/design_1_riscvBram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_riscvBram_0 || ORIG_REF_NAME==design_1_riscvBram_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_picorv32_tut_0_0/design_1_picorv32_tut_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_picorv32_tut_0_0 || ORIG_REF_NAME==design_1_picorv32_tut_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
